from django.urls import path

from cms import views

urlpatterns = [
    path(
        "initiative/<int:initiative>/<str:page_or_update>/",
        views.page_list,
        name="page_list",
    ),
    path(
        "initiative/<int:initiative>/<str:page_or_update>/create/",
        views.page_edit_or_create,
        name="page_create",
    ),
    path(
        "initiative/<int:initiative>/<str:page_or_update>/"
        "<int:page_id>/detail/",
        views.page_detail,
        name="page_detail",
    ),
    path(
        "initiative/<int:initiative>/<str:page_or_update>/<int:page_id>/edit/",
        views.page_edit_or_create,
        name="page_edit",
    ),
    path(
        "initiative/<int:initiative>/<str:page_or_update>/"
        "<int:page_id>/delete/",
        views.page_delete,
        name="page_delete",
    ),
    path(
        "initiative/<int:initiative>/<str:page_or_update>/<int:page_id>/"
        "version/<int:version_id>",
        views.view_version,
        name="view_version",
    ),
    path(
        "initiative/<int:initiative>/<str:page_or_update>/"
        "<int:page_id>/version/current/",
        views.view_current_version,
        name="view_current_version",
    ),
    path(
        "initiative/<int:initiative>/<str:page_or_update>/<int:page_id>/"
        "diff/<int:version_one_id>//<int:version_two_id>/",
        views.diff_versions,
        name="diff_versions",
    ),
    path(
        "update/feed/",
        views.page_update_feed,
        name="page_update_feed",
    ),
    path(
        "site-wide/news/",
        views.sitewide_news,
        name="sitewide_news",
    ),
    path(
        "site-wide/news/config/",
        views.sitewide_news_config,
        name="sitewide_news_config",
    ),
    path(
        "site-wide/news/<int:news_id>/delete/",
        views.sitewide_news_delete,
        name="sitewide_news_delete",
    ),
    path(
        "site-wide/news/order",
        views.sitewide_news_order,
        name="sitewide_news_order",
    ),
    path(
        "site-wide/news/<int:update_id>/view",
        views.news_item,
        name="news_item",
    ),
    path(
        "who-we-are-config",
        views.who_we_are_config,
        name="who_we_are_config",
    ),
    path(
        "who-we-are-entry/<int:entry_id>/delete",
        views.delete_who_we_are_entry,
        name="delete_who_we_are_entry",
    ),
    path(
        "who-we-are-entry/<str:section>/add",
        views.add_who_we_are_entry,
        name="add_who_we_are_entry",
    ),
    path(
        "who-we-are-entry/<str:section>/<int:entry_id>/edit",
        views.add_who_we_are_entry,
        name="edit_who_we_are_entry",
    ),
    path(
        "who-we-are-entries/order",
        views.who_we_are_order,
        name="who_we_are_order",
    ),
    path(
        "fixed_pages/",
        views.fixed_pages,
        name="fixed_pages",
    ),
    path(
        "fixed_page/<str:page_string>/",
        views.fixed_page,
        name="fixed_page",
    ),
    path(
        "all_pages/",
        views.all_pages,
        name="all_pages",
    ),
    path(
        "page_render/<int:page_id>/",
        views.page_render,
        name="page_render",
    ),
    path(
        "homepage_quotes/",
        views.homepage_quotes,
        name="homepage_quotes",
    ),
    path(
        "new_quote/",
        views.new_quote,
        name="new_quote",
    ),
    path(
        "edit_quote/<int:quote_id>/",
        views.new_quote,
        name="edit_quote",
    ),
    path(
        "delete_quote/<int:quote_id>/",
        views.delete_quote,
        name="delete_quote",
    ),
    path(
        "order_quote/",
        views.homepage_quotes_order,
        name="homepage_quotes_order",
    ),
    # note: this type of URL pattern conflicts with the page_or_update if
    # you use "create" at the end
    path(
        "initiative/<int:initiative>/featured_book/new/",
        views.featured_book_create,
        name="featured_book_create",
    ),
    # note: this type of URL pattern conflicts with the page or update delete if
    # you use "delete" at the end
    path(
        "initiative/<int:initiative>/featured_book/<int:fb_id>/nuke/",
        views.featured_book_delete,
        name="featured_book_delete",
    ),
    path(
        "initiative/<int:initiative>/featured_books/setup/",
        views.featured_books,
        name="featured_books",
    ),
    path(
        "order_featured_books/<int:initiative_id>/",
        views.order_featured_books,
        name="featured_books_order",
    ),
    path(
        "site_text/<slug:key>/",
        views.edit_site_text,
        name="edit_site_text",
    ),
    path(
        'site-texts/',
        views.list_site_text,
        name='list_site_text',
    ),
    path(
        'site-texts/<str:key>/<str:lang_code>/',
        views.edit_site_text,
         name='edit_site_text',
    ),
]
