COUNTRY_CHOICES = [
    {
        "Name": "AFGHANISTAN",
        "Code": "AF",
        "Currency": "Afghani",
        "Currency Code": "AFN",
    },
    {
        "Name": "ALBANIA",
        "Code": "AL",
        "Currency": "Lek",
        "Currency Code": "ALL",
    },
    {
        "Name": "ALGERIA",
        "Code": "DZ",
        "Currency": "Algerian Dinar",
        "Currency Code": "DZD",
    },
    {
        "Name": "AMERICAN SAMOA",
        "Code": "AS",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "ANDORRA ",
        "Code": "AD",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "ANGOLA",
        "Code": "AO",
        "Currency": "Kwanza",
        "Currency Code": "AOA",
    },
    {
        "Name": "ANGUILLA",
        "Code": "AI",
        "Currency": "East Carribbean Dollar",
        "Currency Code": "XCD",
    },
    {
        "Name": "ANTARCTICA",
        "Code": "AQ",
        "Currency": "No universal currency",
        "Currency Code": " ",
    },
    {
        "Name": "ANTIGUA AND BARBUDA",
        "Code": "AG",
        "Currency": "East Carribean Dollar",
        "Currency Code": "XCD",
    },
    {
        "Name": "ARGENTINA",
        "Code": "AR",
        "Currency": "Argentine Peso",
        "Currency Code": "ARS",
    },
    {
        "Name": "ARMENIA",
        "Code": "AM",
        "Currency": "Armenian Dram",
        "Currency Code": "AMD",
    },
    {
        "Name": "ARUBA",
        "Code": "AW",
        "Currency": "Aruban Guilder",
        "Currency Code": "AWG",
    },
    {
        "Name": "AUSTRALIA",
        "Code": "AU",
        "Currency": "Australian Dollar",
        "Currency Code": "AUD",
    },
    {
        "Name": "AUSTRIA",
        "Code": "AT",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "AZERBAIJAN",
        "Code": "AZ",
        "Currency": "Azerbaijanian Manat",
        "Currency Code": "AZM",
    },
    {
        "Name": "BAHAMAS",
        "Code": "BS",
        "Currency": "Bahamian Dollar",
        "Currency Code": "BSD",
    },
    {
        "Name": "BAHRAIN",
        "Code": "BH",
        "Currency": "Bahraini Dinar",
        "Currency Code": "BHD",
    },
    {
        "Name": "BANGLADESH",
        "Code": "BD",
        "Currency": "Taka",
        "Currency Code": "BDT",
    },
    {
        "Name": "BARBADOS",
        "Code": "BB",
        "Currency": "Barbados Dollar",
        "Currency Code": "BBD",
    },
    {
        "Name": "BELARUS",
        "Code": "BY",
        "Currency": "Belarussian Ruble",
        "Currency Code": "BYR",
    },
    {
        "Name": "BELGIUM",
        "Code": "BE",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "BELIZE",
        "Code": "BZ",
        "Currency": "Belize Dollar",
        "Currency Code": "BZD",
    },
    {
        "Name": "BENIN",
        "Code": "BJ",
        "Currency": "CFA Franc BCEAO",
        "Currency Code": "XOF",
    },
    {
        "Name": "BERMUDA",
        "Code": "BM",
        "Currency": "Bermudian Dollar",
        "Currency Code": "BMD",
    },
    {
        "Name": "BHUTAN",
        "Code": "BT",
        "Currency": "Indian Rupee",
        "Currency Code": "INR",
    },
    {
        "Name": "BHUTAN",
        "Code": "BT",
        "Currency": "Ngultrum",
        "Currency Code": "BTN",
    },
    {
        "Name": "BOLIVIA",
        "Code": "BO",
        "Currency": "Boliviano",
        "Currency Code": "BOB",
    },
    {
        "Name": "BOLIVIA",
        "Code": "BO",
        "Currency": "Mvdol",
        "Currency Code": "BOV",
    },
    {
        "Name": "BOSNIA AND HERZEGOVINA",
        "Code": "BA",
        "Currency": "Convertible Marks",
        "Currency Code": "BAM",
    },
    {
        "Name": "BOTSWANA",
        "Code": "BW",
        "Currency": "Pula",
        "Currency Code": "BWP",
    },
    {
        "Name": "BOUVET ISLAND",
        "Code": "BV",
        "Currency": "Norvegian Krone",
        "Currency Code": "NOK",
    },
    {
        "Name": "BRAZIL",
        "Code": "BR",
        "Currency": "Brazilian Real",
        "Currency Code": "BRL",
    },
    {
        "Name": "BRITISH INDIAN OCEAN TERRITORY",
        "Code": "IO",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "BRUNEI DARUSSALAM",
        "Code": "BN",
        "Currency": "Brunei Dollar",
        "Currency Code": "BND",
    },
    {
        "Name": "BULGARIA",
        "Code": "BG",
        "Currency": "Bulgarian Lev",
        "Currency Code": "BGN",
    },
    {
        "Name": "BURKINA FASO",
        "Code": "BF",
        "Currency": "CFA Franc BCEAO",
        "Currency Code": "XOF",
    },
    {
        "Name": "BURUNDI",
        "Code": "BI",
        "Currency": "Burundi Franc",
        "Currency Code": "BIF",
    },
    {
        "Name": "CAMBODIA",
        "Code": "KH",
        "Currency": "Riel",
        "Currency Code": "KHR",
    },
    {
        "Name": "CAMEROON",
        "Code": "CM",
        "Currency": "CFA Franc BEAC",
        "Currency Code": "XAF",
    },
    {
        "Name": "CANADA",
        "Code": "CA",
        "Currency": "Canadian Dollar",
        "Currency Code": "CAD",
    },
    {
        "Name": "CAPE VERDE",
        "Code": "CV",
        "Currency": "Cape Verde Escudo",
        "Currency Code": "CVE",
    },
    {
        "Name": "CAYMAN ISLANDS",
        "Code": "KY",
        "Currency": "Cayman Islands Dollar",
        "Currency Code": "KYD",
    },
    {
        "Name": "CENTRAL AFRICAN REPUBLIC",
        "Code": "CF",
        "Currency": "CFA Franc BEAC",
        "Currency Code": "XAF",
    },
    {
        "Name": "CHAD",
        "Code": "TD",
        "Currency": "CFA Franc BEAC",
        "Currency Code": "XAF",
    },
    {
        "Name": "CHILE",
        "Code": "CL",
        "Currency": "Chilean Peso",
        "Currency Code": "CLP",
    },
    {
        "Name": "CHILE",
        "Code": "CL",
        "Currency": "Unidades de fomento",
        "Currency Code": "CLF",
    },
    {
        "Name": "CHINA",
        "Code": "CN",
        "Currency": "Yuan Renminbi",
        "Currency Code": "CNY",
    },
    {
        "Name": "CHRISTMAS ISLAND",
        "Code": "CX",
        "Currency": "Australian Dollar",
        "Currency Code": "AUD",
    },
    {
        "Name": "COCOS (KEELING) ISLANDS",
        "Code": "CC",
        "Currency": "Australian Dollar",
        "Currency Code": "AUD",
    },
    {
        "Name": "COLOMBIA",
        "Code": "CO",
        "Currency": "Colombian Peso",
        "Currency Code": "COP",
    },
    {
        "Name": "COLOMBIA",
        "Code": "CO",
        "Currency": "Unidad de Valor Real",
        "Currency Code": "COU",
    },
    {
        "Name": "COMOROS",
        "Code": "KM",
        "Currency": "Comoro Franc",
        "Currency Code": "KMF",
    },
    {
        "Name": "CONGO",
        "Code": "CG",
        "Currency": "CFA Franc BEAC",
        "Currency Code": "XAF",
    },
    {
        "Name": "CONGO, THE DEMOCRATIC REPUBLIC OF",
        "Code": "CD",
        "Currency": "Franc Congolais",
        "Currency Code": "CDF",
    },
    {
        "Name": "COOK ISLANDS",
        "Code": "CK",
        "Currency": "New Zealand Dollar",
        "Currency Code": "NZD",
    },
    {
        "Name": "COSTA RICA",
        "Code": "CR",
        "Currency": "Costa Rican Colon",
        "Currency Code": "CRC",
    },
    {
        "Name": "COTE D'IVOIRE",
        "Code": "CI",
        "Currency": "CFA Franc BCEAO",
        "Currency Code": "XOF",
    },
    {
        "Name": "CROATIA",
        "Code": "HR",
        "Currency": "Croatian kuna",
        "Currency Code": "HRK",
    },
    {
        "Name": "CUBA",
        "Code": "CU",
        "Currency": "Cuban Peso",
        "Currency Code": "CUP",
    },
    {
        "Name": "CYPRUS",
        "Code": "CY",
        "Currency": "Cyprus Pound",
        "Currency Code": "CYP",
    },
    {
        "Name": "CZECH REPUBLIC",
        "Code": "CZ",
        "Currency": "Czech Koruna",
        "Currency Code": "CZK",
    },
    {
        "Name": "DENMARK",
        "Code": "DK",
        "Currency": "Danish Krone",
        "Currency Code": "DKK",
    },
    {
        "Name": "DJIBOUTI",
        "Code": "DJ",
        "Currency": "Djibouti Franc",
        "Currency Code": "DJF",
    },
    {
        "Name": "DOMINICA",
        "Code": "DM",
        "Currency": "East Caribbean Dollar",
        "Currency Code": "XCD",
    },
    {
        "Name": "DOMINICAN REPUBLIC",
        "Code": "DO",
        "Currency": "Dominican Peso",
        "Currency Code": "DOP",
    },
    {
        "Name": "ECUADOR",
        "Code": "EC",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "EGYPT",
        "Code": "EG",
        "Currency": "Egyptian Pound",
        "Currency Code": "EGP",
    },
    {
        "Name": "EL SALVADOR",
        "Code": "SV",
        "Currency": "El Salvador Colon",
        "Currency Code": "SVC",
    },
    {
        "Name": "EL SALVADOR",
        "Code": "SV",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "EQUATORIAL GUINEA",
        "Code": "GQ",
        "Currency": "CFA Franc BEAC",
        "Currency Code": "XAF",
    },
    {
        "Name": "ERITREA",
        "Code": "ER",
        "Currency": "Nakfa",
        "Currency Code": "ERN",
    },
    {
        "Name": "ESTONIA",
        "Code": "EE",
        "Currency": "Kroon",
        "Currency Code": "EEK",
    },
    {
        "Name": "ETHIOPIA",
        "Code": "ET",
        "Currency": "Ethiopian Birr",
        "Currency Code": "ETB",
    },
    {
        "Name": "EUROZONE",
        "Code": "EUR",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "FALKLAND ISLANDS (MALVINAS)",
        "Code": "FK",
        "Currency": "Falkland Islands Pound",
        "Currency Code": "FKP",
    },
    {
        "Name": "FAROE ISLANDS",
        "Code": "FO",
        "Currency": "Danish Krone",
        "Currency Code": "DKK",
    },
    {
        "Name": "FIJI",
        "Code": "FJ",
        "Currency": "Fiji Dollar",
        "Currency Code": "FJD",
    },
    {
        "Name": "FINLAND ",
        "Code": "FI",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "FRANCE",
        "Code": "FR",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "FRENCH GUIANA ",
        "Code": "GF",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "FRENCH POLYNESIA",
        "Code": "PF",
        "Currency": "CFP Franc",
        "Currency Code": "XPF",
    },
    {
        "Name": "FRENCH SOUTHERN TERRITORIES",
        "Code": "TF",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "GABON",
        "Code": "GA",
        "Currency": "CFA Franc BEAC",
        "Currency Code": "XAF",
    },
    {
        "Name": "GAMBIA",
        "Code": "GM",
        "Currency": "Dalasi",
        "Currency Code": "GMD",
    },
    {
        "Name": "GEORGIA",
        "Code": "GE",
        "Currency": "Lari",
        "Currency Code": "GEL",
    },
    {
        "Name": "GERMANY",
        "Code": "DE",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {"Name": "GHANA", "Code": "GH", "Currency": "Cedi", "Currency Code": "GHC"},
    {
        "Name": "GIBRALTAR",
        "Code": "GI",
        "Currency": "Gibraltar Pound",
        "Currency Code": "GIP",
    },
    {
        "Name": "GREECE",
        "Code": "GR",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "GREENLAND",
        "Code": "GL",
        "Currency": "Danish Krone",
        "Currency Code": "DKK",
    },
    {
        "Name": "GRENADA",
        "Code": "GD",
        "Currency": "East Caribbean Dollar",
        "Currency Code": "XCD",
    },
    {
        "Name": "GUADELOUPE",
        "Code": "GP",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "GUAM",
        "Code": "GU",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "GUATEMALA",
        "Code": "GT",
        "Currency": "Quetzal",
        "Currency Code": "GTQ",
    },
    {
        "Name": "GUINEA",
        "Code": "GN",
        "Currency": "Guinea Franc",
        "Currency Code": "GNF",
    },
    {
        "Name": "GUINEA-BISSAU",
        "Code": "GW",
        "Currency": "Guinea-Bissau Peso",
        "Currency Code": "GWP",
    },
    {
        "Name": "GUINEA-BISSAU",
        "Code": "GW",
        "Currency": "CFA Franc BCEAO",
        "Currency Code": "XOF",
    },
    {
        "Name": "GUYANA",
        "Code": "GY",
        "Currency": "Guyana Dollar",
        "Currency Code": "GYD",
    },
    {
        "Name": "HAITI",
        "Code": "HT",
        "Currency": "Gourde",
        "Currency Code": "HTG",
    },
    {
        "Name": "HAITI",
        "Code": "HT",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "HEARD ISLAND AND MCDONALD ISLANDS",
        "Code": "HM",
        "Currency": "Australian Dollar",
        "Currency Code": "AUD",
    },
    {
        "Name": "HOLY SEE (VATICAN CITY STATE)",
        "Code": "VA",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "HONDURAS",
        "Code": "HN",
        "Currency": "Lempira",
        "Currency Code": "HNL",
    },
    {
        "Name": "HONG KONG",
        "Code": "HK",
        "Currency": "Hong Kong Dollar",
        "Currency Code": "HKD",
    },
    {
        "Name": "HUNGARY",
        "Code": "HU",
        "Currency": "Forint",
        "Currency Code": "HUF",
    },
    {
        "Name": "ICELAND",
        "Code": "IS",
        "Currency": "Iceland Krona",
        "Currency Code": "ISK",
    },
    {
        "Name": "INDIA",
        "Code": "IN",
        "Currency": "Indian Rupee",
        "Currency Code": "INR",
    },
    {
        "Name": "INDONESIA",
        "Code": "ID",
        "Currency": "Rupiah",
        "Currency Code": "IDR",
    },
    {
        "Name": "IRAN, ISLAMIC REPUBLIC OF",
        "Code": "IR",
        "Currency": "Iranian Rial",
        "Currency Code": "IRR",
    },
    {
        "Name": "IRAQ",
        "Code": "IQ",
        "Currency": "Iraqi Dinar",
        "Currency Code": "IQD",
    },
    {
        "Name": "IRELAND",
        "Code": "IE",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "ISRAEL",
        "Code": "IL",
        "Currency": "New Israeli Sheqel",
        "Currency Code": "ILS",
    },
    {"Name": "ITALY", "Code": "IT", "Currency": "Euro", "Currency Code": "EUR"},
    {
        "Name": "JAMAICA",
        "Code": "JM",
        "Currency": "Jamaican Dollar",
        "Currency Code": "JMD",
    },
    {"Name": "JAPAN", "Code": "JP", "Currency": "Yen", "Currency Code": "JPY"},
    {
        "Name": "JORDAN",
        "Code": "JO",
        "Currency": "Jordanian Dinar",
        "Currency Code": "JOD",
    },
    {
        "Name": "KAZAKHSTAN",
        "Code": "KZ",
        "Currency": "Tenge",
        "Currency Code": "KZT",
    },
    {
        "Name": "KENYA",
        "Code": "KE",
        "Currency": "Kenyan Shilling",
        "Currency Code": "KES",
    },
    {
        "Name": "KIRIBATI",
        "Code": "KI",
        "Currency": "Australian Dollar",
        "Currency Code": "AUD",
    },
    {
        "Name": "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
        "Code": "KP",
        "Currency": "North Korean Won",
        "Currency Code": "KPW",
    },
    {
        "Name": "KOREA, REPUBLIC OF",
        "Code": "KR",
        "Currency": "Won",
        "Currency Code": "KRW",
    },
    {
        "Name": "KUWAIT",
        "Code": "KW",
        "Currency": "Kuwaiti Dinar",
        "Currency Code": "KWD",
    },
    {
        "Name": "KYRGYZSTAN",
        "Code": "KG",
        "Currency": "Som",
        "Currency Code": "KGS",
    },
    {
        "Name": "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
        "Code": "LA",
        "Currency": "Kip",
        "Currency Code": "LAK",
    },
    {
        "Name": "LATVIA",
        "Code": "LV",
        "Currency": "Latvian Lats",
        "Currency Code": "LVL",
    },
    {
        "Name": "LEBANON",
        "Code": "LB",
        "Currency": "Lebanese Pound",
        "Currency Code": "LBP",
    },
    {
        "Name": "LESOTHO",
        "Code": "LS",
        "Currency": "Rand",
        "Currency Code": "ZAR",
    },
    {
        "Name": "LESOTHO",
        "Code": "LS",
        "Currency": "Loti",
        "Currency Code": "LSL",
    },
    {
        "Name": "LIBERIA",
        "Code": "LR",
        "Currency": "Liberian Dollar",
        "Currency Code": "LRD",
    },
    {
        "Name": "LIBYAN ARAB JAMAHIRIYA",
        "Code": "LY",
        "Currency": "Lybian Dinar",
        "Currency Code": "LYD",
    },
    {
        "Name": "LIECHTENSTEIN",
        "Code": "LI",
        "Currency": "Swiss Franc",
        "Currency Code": "CHF",
    },
    {
        "Name": "LITHUANIA",
        "Code": "LT",
        "Currency": "Lithuanian Litas",
        "Currency Code": "LTL",
    },
    {
        "Name": "LUXEMBOURG",
        "Code": "LU",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "MACAO",
        "Code": "MO",
        "Currency": "Pataca",
        "Currency Code": "MOP",
    },
    {
        "Name": "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
        "Code": "MK",
        "Currency": "Denar",
        "Currency Code": "MKD",
    },
    {
        "Name": "MADAGASCAR",
        "Code": "MG",
        "Currency": "Ariary",
        "Currency Code": "MGA",
    },
    {
        "Name": "MADAGASCAR",
        "Code": "MG",
        "Currency": "Malagasy Franc",
        "Currency Code": "MGF",
    },
    {
        "Name": "MALAWI",
        "Code": "MW",
        "Currency": "Kwacha",
        "Currency Code": "MWK",
    },
    {
        "Name": "MALAYSIA",
        "Code": "MY",
        "Currency": "Malaysian Ringgit",
        "Currency Code": "MYR",
    },
    {
        "Name": "MALDIVES",
        "Code": "MV",
        "Currency": "Rufiyaa",
        "Currency Code": "MVR",
    },
    {
        "Name": "MALI",
        "Code": "ML",
        "Currency": "CFA Franc BCEAO",
        "Currency Code": "XOF",
    },
    {
        "Name": "MALTA",
        "Code": "MT",
        "Currency": "Maltese Lira",
        "Currency Code": "MTL",
    },
    {
        "Name": "MARSHALL ISLANDS",
        "Code": "MH",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "MARTINIQUE",
        "Code": "MQ",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "MAURITANIA",
        "Code": "MR",
        "Currency": "Ouguiya",
        "Currency Code": "MRO",
    },
    {
        "Name": "MAURITIUS",
        "Code": "MU",
        "Currency": "Mauritius Rupee",
        "Currency Code": "MUR",
    },
    {
        "Name": "MAYOTTE",
        "Code": "YT",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "MEXICO",
        "Code": "MX",
        "Currency": "Mexican Peso",
        "Currency Code": "MXN",
    },
    {
        "Name": "MEXICO",
        "Code": "MX",
        "Currency": "Mexican Unidad de Inversion (UDI)",
        "Currency Code": "MXV",
    },
    {
        "Name": "MICRONESIA, FEDERATED STATES OF",
        "Code": "FM",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "MOLDOVA, REPUBLIC OF",
        "Code": "MD",
        "Currency": "Moldovan Leu",
        "Currency Code": "MDL",
    },
    {
        "Name": "MONACO",
        "Code": "MC",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "MONGOLIA",
        "Code": "MN",
        "Currency": "Tugrik",
        "Currency Code": "MNT",
    },
    {
        "Name": "MONTSERRAT",
        "Code": "MS",
        "Currency": "East Caribbean Dollar",
        "Currency Code": "XCD",
    },
    {
        "Name": "MOROCCO",
        "Code": "MA",
        "Currency": "Moroccan Dirham",
        "Currency Code": "MAD",
    },
    {
        "Name": "MOZAMBIQUE",
        "Code": "MZ",
        "Currency": "Metical",
        "Currency Code": "MZM",
    },
    {
        "Name": "MYANMAR",
        "Code": "MM",
        "Currency": "Kyat",
        "Currency Code": "MMK",
    },
    {
        "Name": "NAMIBIA",
        "Code": "NA",
        "Currency": "Rand",
        "Currency Code": "ZAR",
    },
    {
        "Name": "NAMIBIA",
        "Code": "NA",
        "Currency": "Namibia Dollar",
        "Currency Code": "NAD",
    },
    {
        "Name": "NAURU",
        "Code": "NR",
        "Currency": "Australian Dollar",
        "Currency Code": "AUD",
    },
    {
        "Name": "NEPAL",
        "Code": "NP",
        "Currency": "Nepalese Rupee",
        "Currency Code": "NPR",
    },
    {
        "Name": "NETHERLANDS",
        "Code": "NL",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "NETHERLANDS ANTILLES",
        "Code": "AN",
        "Currency": "Netherlands Antillan Guilder",
        "Currency Code": "ANG",
    },
    {
        "Name": "NEW CALEDONIA",
        "Code": "NC",
        "Currency": "CFP Franc",
        "Currency Code": "XPF",
    },
    {
        "Name": "NEW ZEALAND",
        "Code": "NZ",
        "Currency": "New Zealand Dollar",
        "Currency Code": "NZD",
    },
    {
        "Name": "NICARAGUA",
        "Code": "NI",
        "Currency": "Cordoba Oro",
        "Currency Code": "NIO",
    },
    {
        "Name": "NIGER",
        "Code": "NE",
        "Currency": "CFA Franc BCEAO",
        "Currency Code": "XOF",
    },
    {
        "Name": "NIGERIA",
        "Code": "NG",
        "Currency": "Naira",
        "Currency Code": "NGN",
    },
    {
        "Name": "NIUE",
        "Code": "NU",
        "Currency": "New Zealand Dollar",
        "Currency Code": "NZD",
    },
    {
        "Name": "NORFOLK ISLAND",
        "Code": "NF",
        "Currency": "Australian Dollar",
        "Currency Code": "AUD",
    },
    {
        "Name": "NORTHERN MARIANA ISLANDS",
        "Code": "MP",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "NORWAY",
        "Code": "NO",
        "Currency": "Norwegian Krone",
        "Currency Code": "NOK",
    },
    {
        "Name": "OMAN",
        "Code": "OM",
        "Currency": "Rial Omani",
        "Currency Code": "OMR",
    },
    {
        "Name": "PAKISTAN",
        "Code": "PK",
        "Currency": "Pakistan Rupee",
        "Currency Code": "PKR",
    },
    {
        "Name": "PALAU",
        "Code": "PW",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "PALESTINIAN TERRITORY, OCCUPIED",
        "Code": "PS",
        "Currency": " ",
        "Currency Code": " ",
    },
    {
        "Name": "PANAMA",
        "Code": "PA",
        "Currency": "Balboa",
        "Currency Code": "PAB",
    },
    {
        "Name": "PANAMA",
        "Code": "PA",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "PAPUA NEW GUINEA",
        "Code": "PG",
        "Currency": "Kina",
        "Currency Code": "PGK",
    },
    {
        "Name": "PARAGUAY",
        "Code": "PY",
        "Currency": "Guarani",
        "Currency Code": "PYG",
    },
    {
        "Name": "PERU",
        "Code": "PE",
        "Currency": "Nuevo Sol",
        "Currency Code": "PEN",
    },
    {
        "Name": "PHILIPPINES",
        "Code": "PH",
        "Currency": "Philippine Peso",
        "Currency Code": "PHP",
    },
    {
        "Name": "PITCAIRN",
        "Code": "PN",
        "Currency": "New Zealand Dollar",
        "Currency Code": "NZD",
    },
    {
        "Name": "POLAND",
        "Code": "PL",
        "Currency": "Zloty",
        "Currency Code": "PLN",
    },
    {
        "Name": "PORTUGAL",
        "Code": "PT",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "PUERTO RICO",
        "Code": "PR",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "QATAR",
        "Code": "QA",
        "Currency": "Qatari Rial",
        "Currency Code": "QAR",
    },
    {
        "Name": "REUNION",
        "Code": "RE",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "ROMANIA",
        "Code": "RO",
        "Currency": "Leu",
        "Currency Code": "ROL",
    },
    {
        "Name": "RUSSIAN FEDERATION",
        "Code": "RU",
        "Currency": "Russian Ruble",
        "Currency Code": "RUR",
    },
    {
        "Name": "RUSSIAN FEDERATION",
        "Code": "RU",
        "Currency": "Russian Ruble",
        "Currency Code": "RUB",
    },
    {
        "Name": "RWANDA",
        "Code": "RW",
        "Currency": "Rwanda Franc",
        "Currency Code": "RWF",
    },
    {
        "Name": "SAINT HELENA",
        "Code": "SH",
        "Currency": "Saint Helena Pound",
        "Currency Code": "SHP",
    },
    {
        "Name": "SAINT KITTS AND NEVIS",
        "Code": "KN",
        "Currency": "East Caribbean Dollar",
        "Currency Code": "XCD",
    },
    {
        "Name": "SAINT LUCIA",
        "Code": "LC",
        "Currency": "East Caribbean Dollar",
        "Currency Code": "XCD",
    },
    {
        "Name": "SAINT PIERRE AND MIQUELON",
        "Code": "PM",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "SAINT VINCENT AND THE GRENADINES",
        "Code": "VC",
        "Currency": "East Caribbean Dollar",
        "Currency Code": "XCD",
    },
    {"Name": "SAMOA", "Code": "WS", "Currency": "Tala", "Currency Code": "WST"},
    {
        "Name": "SAN MARINO",
        "Code": "SM",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "SAO TOME AND PRINCIPE",
        "Code": "ST",
        "Currency": "Dobra",
        "Currency Code": "STD",
    },
    {
        "Name": "SAUDI ARABIA",
        "Code": "SA",
        "Currency": "Saudi Riyal",
        "Currency Code": "SAR",
    },
    {
        "Name": "SENEGAL",
        "Code": "SN",
        "Currency": "CFA Franc BCEAO",
        "Currency Code": "XOF",
    },
    {
        "Name": "SERBIA & MONTENEGRO",
        "Code": "CS",
        "Currency": "Euro",
        "Currency Code": "EUR",
    },
    {
        "Name": "SERBIA & MONTENEGRO",
        "Code": "CS",
        "Currency": "Serbian Dinar",
        "Currency Code": "CSD",
    },
    {
        "Name": "SEYCHELLES",
        "Code": "SC",
        "Currency": "Seychelles Rupee",
        "Currency Code": "SCR",
    },
    {
        "Name": "SIERRA LEONE",
        "Code": "SL",
        "Currency": "Leone",
        "Currency Code": "SLL",
    },
    {
        "Name": "SINGAPORE",
        "Code": "SG",
        "Currency": "Singapore Dollar",
        "Currency Code": "SGD",
    },
    {
        "Name": "SLOVAKIA",
        "Code": "SK",
        "Currency": "Slovak Koruna",
        "Currency Code": "SKK",
    },
    {
        "Name": "SLOVENIA",
        "Code": "SI",
        "Currency": "Tolar",
        "Currency Code": "SIT",
    },
    {
        "Name": "SOLOMON ISLANDS",
        "Code": "SB",
        "Currency": "Solomon Islands Dollar",
        "Currency Code": "SBD",
    },
    {
        "Name": "SOMALIA",
        "Code": "SO",
        "Currency": "Somali Shilling",
        "Currency Code": "SOS",
    },
    {
        "Name": "SOUTH AFRICA",
        "Code": "ZA",
        "Currency": "Rand",
        "Currency Code": "ZAR",
    },
    {
        "Name": "SOUTH GEORGIA & THE SOUTH SANDWICH ISLANDS",
        "Code": "GS",
        "Currency": " ",
        "Currency Code": " ",
    },
    {"Name": "SPAIN", "Code": "ES", "Currency": "Euro", "Currency Code": "EUR"},
    {
        "Name": "SRI LANKA",
        "Code": "LK",
        "Currency": "Sri Lanka Rupee",
        "Currency Code": "LKR",
    },
    {
        "Name": "SUDAN",
        "Code": "SD",
        "Currency": "Sudanese Dinar",
        "Currency Code": "SDD",
    },
    {
        "Name": "SURINAME",
        "Code": "SR",
        "Currency": "Suriname Dollar",
        "Currency Code": "SRD",
    },
    {
        "Name": "SVALBARD AND JAN MAYEN",
        "Code": "SJ",
        "Currency": "Norwegian Krone",
        "Currency Code": "NOK",
    },
    {
        "Name": "SWAZILAND",
        "Code": "SZ",
        "Currency": "Lilangeni",
        "Currency Code": "SZL",
    },
    {
        "Name": "SWEDEN",
        "Code": "SE",
        "Currency": "Swedish Krona",
        "Currency Code": "SEK",
    },
    {
        "Name": "SWITZERLAND",
        "Code": "CH",
        "Currency": "Swiss Franc",
        "Currency Code": "CHF",
    },
    {
        "Name": "SYRIAN ARAB REPUBLIC",
        "Code": "SY",
        "Currency": "Syrian Pound",
        "Currency Code": "SYP",
    },
    {
        "Name": "TAIWAN, PROVINCE OF CHINA",
        "Code": "TW",
        "Currency": "New Taiwan Dollar",
        "Currency Code": "TWD",
    },
    {
        "Name": "TAJIKISTAN",
        "Code": "TJ",
        "Currency": "Somoni",
        "Currency Code": "TJS",
    },
    {
        "Name": "TANZANIA, UNITED REPUBLIC OF",
        "Code": "TZ",
        "Currency": "Tanzanian Shilling",
        "Currency Code": "TZS",
    },
    {
        "Name": "THAILAND",
        "Code": "TH",
        "Currency": "Baht",
        "Currency Code": "THB",
    },
    {
        "Name": "TIMOR-LESTE",
        "Code": "TL",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "TOGO",
        "Code": "TG",
        "Currency": "CFA Franc BCEAO",
        "Currency Code": "XOF",
    },
    {
        "Name": "TOKELAU",
        "Code": "TK",
        "Currency": "New Zealand Dollar",
        "Currency Code": "NZD",
    },
    {
        "Name": "TONGA",
        "Code": "TO",
        "Currency": "Pa�anga",
        "Currency Code": "TOP",
    },
    {
        "Name": "TRINIDAD AND TOBAGO",
        "Code": "TT",
        "Currency": "Trinidad and Tobago Dollar",
        "Currency Code": "TTD",
    },
    {
        "Name": "TUNISIA",
        "Code": "TN",
        "Currency": "Tunisian Dinar",
        "Currency Code": "TND",
    },
    {
        "Name": "TURKEY",
        "Code": "TR",
        "Currency": "Turkish Lira",
        "Currency Code": "TRL",
    },
    {
        "Name": "TURKMENISTAN",
        "Code": "TM",
        "Currency": "Manat",
        "Currency Code": "TMM",
    },
    {
        "Name": "TURKS AND CAICOS ISLANDS",
        "Code": "TC",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "TUVALU",
        "Code": "TV",
        "Currency": "Australian Dollar",
        "Currency Code": "AUD",
    },
    {
        "Name": "UGANDA",
        "Code": "UG",
        "Currency": "Uganda Shilling",
        "Currency Code": "UGX",
    },
    {
        "Name": "UKRAINE",
        "Code": "UA",
        "Currency": "Hryvnia",
        "Currency Code": "UAH",
    },
    {
        "Name": "UNITED ARAB EMIRATES",
        "Code": "AE",
        "Currency": "UAE Dirham",
        "Currency Code": "AED",
    },
    {
        "Name": "UNITED KINGDOM",
        "Code": "GB",
        "Currency": "Pound Sterling",
        "Currency Code": "GBP",
    },
    {
        "Name": "UNITED STATES",
        "Code": "US",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "UNITED STATES",
        "Code": "US",
        "Currency": "US Dollar (Same day)",
        "Currency Code": "USS",
    },
    {
        "Name": "UNITED STATES",
        "Code": "US",
        "Currency": "US Dollar (Next day)",
        "Currency Code": "USN",
    },
    {
        "Name": "UNITED STATES MINOR OUTLYING ISLANDS",
        "Code": "UM",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "URUGUAY",
        "Code": "UY",
        "Currency": "Peso Uruguayo",
        "Currency Code": "UYU",
    },
    {
        "Name": "UZBEKISTAN",
        "Code": "UZ",
        "Currency": "Uzbekistan Sum",
        "Currency Code": "UZS",
    },
    {
        "Name": "VANUATU",
        "Code": "VU",
        "Currency": "Vatu",
        "Currency Code": "VUV",
    },
    {
        "Name": "VENEZUELA",
        "Code": "VE",
        "Currency": "Bolivar",
        "Currency Code": "VEB",
    },
    {
        "Name": "VIET NAM",
        "Code": "VN",
        "Currency": "Dong",
        "Currency Code": "VND",
    },
    {
        "Name": "VIRGIN ISLANDS, BRITISH",
        "Code": "VG",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "VIRGIN ISLANDS, U.S.",
        "Code": "VI",
        "Currency": "US Dollar",
        "Currency Code": "USD",
    },
    {
        "Name": "WALLIS AND FUTUNA",
        "Code": "WF",
        "Currency": "CFP Franc",
        "Currency Code": "XPF",
    },
    {
        "Name": "WESTERN SAHARA",
        "Code": "EH",
        "Currency": "Moroccan Dirham",
        "Currency Code": "MAD",
    },
    {
        "Name": "YEMEN",
        "Code": "YE",
        "Currency": "Yemeni Rial",
        "Currency Code": "YER",
    },
    {
        "Name": "ZAMBIA",
        "Code": "ZM",
        "Currency": "Kwacha",
        "Currency Code": "ZMK",
    },
    {
        "Name": "ZIMBABWE",
        "Code": "ZW",
        "Currency": "Zimbabwe Dollar",
        "Currency Code": "ZWD",
    },
]
