# Generated by Django 3.2.4 on 2021-08-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('contribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution', models.TextField(blank=True, null=True)),
                ('contribution_ordinal', models.IntegerField(blank=True, null=True)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('thoth_id', models.UUIDField()),
                ('contribution_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('contributor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('orcid', models.UUIDField(blank=True, null=True)),
                ('thoth_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_type', models.CharField(blank=True, max_length=255, null=True)),
                ('fullTitle', models.TextField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('cover_caption', models.TextField(blank=True, null=True)),
                ('thoth_id', models.UUIDField()),
            ],
        ),
    ]
