# Generated by Django 3.2.4 on 2021-08-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0002_rename_fulltitle_work_full_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='full_name',
        ),
        migrations.AddField(
            model_name='contribution',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thoth.contributor'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thoth.work'),
        ),
    ]
