# Generated by Django 3.2.4 on 2021-08-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0003_auto_20210815_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='orcid',
            field=models.URLField(blank=True, null=True),
        ),
    ]
