# Generated by Django 3.2.4 on 2021-08-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0006_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_ordinal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
