# Generated by Django 3.2.4 on 2021-08-16 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0008_bic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='BIC_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thoth.bic'),
        ),
    ]
