# Generated by Django 3.2.4 on 2021-08-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0009_subject_bic_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=255)),
            ],
        ),
    ]
