# Generated by Django 3.2.4 on 2021-08-16 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0010_thema'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='thema_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thoth.thema'),
        ),
    ]
