# Generated by Django 3.2.4 on 2021-08-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0011_subject_thema_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BISAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'BISAC Code',
                'verbose_name_plural': 'BISAC Codes',
            },
        ),
        migrations.AlterModelOptions(
            name='bic',
            options={'verbose_name': 'BIC Code', 'verbose_name_plural': 'BIC Codes'},
        ),
        migrations.AlterModelOptions(
            name='thema',
            options={'verbose_name': 'Thema Code', 'verbose_name_plural': 'Thema Codes'},
        ),
    ]
