# Generated by Django 3.2.4 on 2021-08-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0012_auto_20210816_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='BISAC_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thoth.bisac'),
        ),
    ]
