# Generated by Django 3.2.4 on 2021-08-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0013_subject_bisac_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='published_date',
            field=models.CharField(default='n.d.', max_length=255),
        ),
    ]
