# Generated by Django 3.2.4 on 2021-08-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0014_work_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='long_abstract',
            field=models.TextField(default=''),
        ),
    ]
