# Generated by Django 3.2.4 on 2021-08-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0015_work_long_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='license',
            field=models.CharField(default='', max_length=255),
        ),
    ]
