# Generated by Django 3.2.4 on 2021-08-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0016_work_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='short_abstract',
            field=models.TextField(default=''),
        ),
    ]
