# Generated by Django 3.2.4 on 2021-08-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0017_work_short_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='landing_page',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
