# Generated by Django 3.2.4 on 2021-08-30 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thoth', '0018_work_landing_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThothSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_new', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThothSearchElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('BI', 'BIC Subject Code'), ('TH', 'THEMA Subject Code'), ('BS', 'BISAC Subject Code'), ('KW', 'Keyword'), ('FT', 'Free Text'), ('IT', 'Institution Name')], default='FT', max_length=2)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('text_content', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoth.thothsearch')),
            ],
        ),
    ]
