# Generated by Django 3.2.4 on 2021-10-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0020_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='RORRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ror_id', models.URLField(blank=True, null=True)),
                ('institution_name', models.TextField(blank=True, null=True)),
                ('grid_id', models.CharField(blank=True, max_length=255, null=True)),
                ('aliases', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
