# Generated by Django 3.2.4 on 2021-10-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0021_rorrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='rorrecord',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
