# Generated by Django 3.2.8 on 2021-12-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0023_auto_20211024_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoth_id', models.UUIDField()),
                ('thoth_instance', models.URLField(default='https://api.thoth.pub')),
                ('project_name', models.TextField(blank=True, null=True)),
                ('project_shortname', models.TextField(blank=True, null=True)),
                ('institution', models.TextField(blank=True, null=True)),
                ('grant_number', models.TextField(blank=True, null=True)),
                ('jurisdiction', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoth_id', models.UUIDField()),
                ('thoth_instance', models.URLField(default='https://api.thoth.pub')),
                ('institution_name', models.TextField(blank=True, null=True)),
                ('doi', models.TextField(blank=True, null=True)),
                ('ror', models.TextField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
