# Generated by Django 3.2.8 on 2021-12-02 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0024_funding_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thoth.work'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thoth.institution'),
        ),
    ]
