# Generated by Django 3.2.8 on 2021-12-02 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0025_auto_20211202_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thoth.institution'),
        ),
    ]
