# Generated by Django 3.2.8 on 2021-12-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0026_alter_contribution_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='institution',
        ),
        migrations.AddField(
            model_name='contribution',
            name='institutions',
            field=models.ManyToManyField(blank=True, null=True, to='thoth.Institution'),
        ),
    ]
