# Generated by Django 3.2.8 on 2021-12-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0028_alter_contribution_institutions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
