# Generated by Django 3.2.8 on 2022-05-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0029_countrystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoth.work')),
            ],
        ),
    ]
