# Generated by Django 3.2.8 on 2022-05-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0030_worknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='thothsearch',
            name='display_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='thothsearchelement',
            name='search_type',
            field=models.CharField(choices=[('BI', 'BIC Subject Code'), ('TH', 'THEMA Subject Code'), ('BS', 'BISAC Subject Code'), ('KW', 'Keyword'), ('AU', 'Author'), ('FT', 'Free Text'), ('IT', 'Institution Name')], default='FT', max_length=2),
        ),
    ]
