# Generated by Django 3.2.8 on 2022-05-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0031_auto_20220521_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thothsearch',
            options={'verbose_name_plural': 'Thoth Searches'},
        ),
    ]
