# Generated by Django 3.2.8 on 2026-07-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='body_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
