# Generated by Django 3.2.4 on 2021-09-07 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_bleach.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initiatives', '0004_initiative_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocab', '0004_auto_20210815_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Description of the banding.', max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BandingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fte', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BasePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the package', max_length=255)),
                ('description', django_bleach.models.BleachField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, help_text='If unchecked, this package will not be available for signup.')),
                ('banding_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.bandingtype')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=4)),
                ('currency', models.CharField(help_text='Use the currency code eg. GBP or USD', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MetaPackage',
            fields=[
                ('basepackage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='package.basepackage')),
            ],
            bases=('package.basepackage',),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(help_text='Value in the currency of the selected country')),
                ('default_currency', models.CharField(help_text='If this is a default price (e.g. it has no country) add a currency here using the three digit code. For example: USD or GBP', max_length=3)),
                ('banding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.banding')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='package.country')),
            ],
        ),
        migrations.AddField(
            model_name='banding',
            name='banding_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.bandingtype'),
        ),
        migrations.AddField(
            model_name='banding',
            name='fte_vocab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocab.bandingvocab'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('basepackage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='package.basepackage')),
                ('default_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.country')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.initiative')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=('package.basepackage',),
        ),
        migrations.CreateModel(
            name='MetaPackageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=99)),
                ('meta_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.metapackage')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.AddField(
            model_name='metapackage',
            name='packages',
            field=models.ManyToManyField(through='package.MetaPackageLink', to='package.Package'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of your basket', max_length=255)),
                ('session_id', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meta_packages', models.ManyToManyField(blank=True, to='package.MetaPackage')),
                ('packages', models.ManyToManyField(blank=True, to='package.Package')),
            ],
        ),
        migrations.AddField(
            model_name='banding',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package'),
        ),
    ]
