# Generated by Django 3.2.4 on 2021-10-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_auto_20210815_1554'),
        ('package', '0002_bandingtype_vocabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandingtype',
            name='vocabs',
            field=models.ManyToManyField(blank=True, to='vocab.BandingVocab'),
        ),
    ]
