# Generated by Django 3.2.4 on 2021-10-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_alter_bandingtype_vocabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepackage',
            name='active',
            field=models.BooleanField(default=False, help_text='If unchecked, this package will not be available for signup.'),
        ),
    ]
