# Generated by Django 3.2.4 on 2021-10-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20211023_1630'),
        ('package', '0004_alter_basepackage_active'),
    ]

    operations = [
    ]
