# Generated by Django 3.2.4 on 2021-10-29 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0005_merge_20211023_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandingtype',
            name='active',
            field=models.BooleanField(default=True, help_text='If active new packages can be created with this Banding Type.'),
        ),
        migrations.AlterField(
            model_name='bandingtype',
            name='is_fte',
            field=models.BooleanField(default=False, help_text='If this Banding Type is FTE related. You should only select FTE Banding Vocabs if True.'),
        ),
        migrations.AlterField(
            model_name='bandingtype',
            name='name',
            field=models.CharField(help_text='Public name of the Banding Type.#,', max_length=255),
        ),
        migrations.CreateModel(
            name='PackageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, upload_to='documents')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
        ),
        migrations.CreateModel(
            name='FrozenPackageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_pdf', models.FileField(blank=True, upload_to='private_documents')),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('original_package_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.packagedocument')),
            ],
        ),
    ]
