# Generated by Django 3.2.4 on 2021-10-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_auto_20211029_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedocument',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
