# Generated by Django 3.2.8 on 2021-11-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_packagedocument_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandingTypeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banding_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.bandingtype')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
        ),
    ]
