# Generated by Django 3.2.8 on 2021-11-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_bandingtypeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandingTypeCurrencyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banding_type_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.bandingtypeentry')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.country')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
        ),
    ]
