# Generated by Django 3.2.8 on 2021-11-06 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0009_bandingtypecurrencyentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageFormElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.aggregateformelement')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
        ),
    ]
