# Generated by Django 3.2.8 on 2021-11-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_packageformelement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frozenpackagedocument',
            name='original_package_document',
        ),
        migrations.AddField(
            model_name='frozenpackagedocument',
            name='subject_line',
            field=models.TextField(blank=True, null=True),
        ),
    ]
