# Generated by Django 3.2.8 on 2021-11-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_packageformelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='meta_only',
            field=models.BooleanField(default=False, help_text='If this package is only available to be added to meta packages check this box.'),
        ),
        migrations.AlterField(
            model_name='metapackage',
            name='packages',
            field=models.ManyToManyField(help_text='Select the packages that will make up this Meta Package.', through='package.MetaPackageLink', to='package.Package'),
        ),
    ]
