# Generated by Django 3.2.8 on 2021-11-27 17:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0012_auto_20211127_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.UUIDField(default=uuid.uuid4)),
                ('valid_period', models.CharField(blank=True, max_length=255, null=True)),
                ('order_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='package.country')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.frozenpackagedocument')),
            ],
        ),
        migrations.CreateModel(
            name='PackageSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('associated_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.order')),
                ('associated_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='package.country')),
            ],
        ),
    ]
