# Generated by Django 3.2.8 on 2021-11-27 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_order_packagesignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.frozenpackagedocument'),
        ),
    ]
