# Generated by Django 3.2.8 on 2021-11-27 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0014_alter_order_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesignup',
            name='signup_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
