# Generated by Django 3.2.8 on 2021-11-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_auto_20211107_1220'),
        ('package', '0015_packagesignup_signup_date'),
    ]

    operations = [
    ]
