# Generated by Django 3.2.8 on 2021-11-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_contact_access_code'),
        ('package', '0016_merge_20211128_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='signup_contacts',
            field=models.ManyToManyField(blank=True, to='access.Contact'),
        ),
    ]
