# Generated by Django 3.2.8 on 2021-12-03 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0016_merge_20211128_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='active',
            field=models.BooleanField(default=True, help_text='If False this basket will not show in active baskets.'),
        ),
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(help_text='The associated basket record for this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.basket'),
        ),
    ]
