# Generated by Django 3.2.8 on 2021-11-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_contact_access_code'),
        ('package', '0017_package_signup_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='access_contacts',
            field=models.ManyToManyField(blank=True, related_name='access_contacts', to='access.Contact'),
        ),
        migrations.AlterField(
            model_name='package',
            name='signup_contacts',
            field=models.ManyToManyField(blank=True, related_name='signup_contacts', to='access.Contact'),
        ),
    ]
