# Generated by Django 3.2.8 on 2021-12-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0017_auto_20211203_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_element_name', models.CharField(help_text='Copied from PackageFormElement as a backup in the event it is deleted.', max_length=300)),
                ('answer', models.TextField()),
                ('form_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.aggregateformelement')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.order')),
            ],
        ),
    ]
