# Generated by Django 3.2.8 on 2021-12-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0018_orderformanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('provisional', 'Provisional'), ('complete', 'Complete'), ('lapsed', 'Lapsed')], default='provisional', max_length=20),
        ),
    ]
