# Generated by Django 3.2.8 on 2021-12-03 12:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0019_auto_20211203_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frozenpackagedocument',
            name='final_zip',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/Users/ajrbyers/Code/intrepid/src/files'), upload_to='private_documents'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('provisional', 'Provisional'), ('complete', 'Complete'), ('lapsed', 'Lapsed')], default='new', max_length=20),
        ),
    ]
