# Generated by Django 3.2.8 on 2021-12-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0018_auto_20211128_1750'),
        ('package', '0020_auto_20211203_1210'),
    ]

    operations = [
    ]
