# Generated by Django 3.2.8 on 2021-12-03 17:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0021_merge_0018_auto_20211128_1750_0020_auto_20211203_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frozenpackagedocument',
            name='final_zip',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/home/martin/Documents/Programming/intrepid/src/files'), upload_to='private_documents'),
        ),
    ]
