# Generated by Django 3.2.8 on 2021-12-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0022_alter_frozenpackagedocument_final_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banding',
            old_name='fte_vocab',
            new_name='vocab',
        ),
        migrations.RemoveField(
            model_name='banding',
            name='name',
        ),
    ]
