# Generated by Django 3.2.8 on 2021-12-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0023_auto_20211205_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesignup',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('provisional', 'Provisional'), ('complete', 'Complete'), ('lapsed', 'Lapsed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='basepackage',
            name='active',
            field=models.BooleanField(default=False, help_text='If unchecked, this package will be unavailable for signup.'),
        ),
    ]
