# Generated by Django 3.2.8 on 2021-12-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_alter_initiative_users'),
        ('package', '0025_packagesignuporderformanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banding',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandings', to='package.package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='initiatives.initiative'),
        ),
        migrations.AlterField(
            model_name='price',
            name='banding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='package.banding'),
        ),
        migrations.AlterField(
            model_name='price',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='package.country'),
        ),
    ]
