# Generated by Django 3.2.8 on 2021-12-09 10:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0026_auto_20211206_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frozenpackagedocument',
            name='final_zip',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/Users/ajrbyers/Code/intrepid/src/files'), upload_to='private_documents'),
        ),
    ]
