# Generated by Django 3.2.8 on 2022-01-26 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0027_alter_frozenpackagedocument_final_zip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-order_date',)},
        ),
        migrations.AddField(
            model_name='packagesignup',
            name='initiative_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagesignup',
            name='initiative_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagesignup',
            name='organisation_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
