# Generated by Django 3.2.8 on 2022-01-26 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0028_auto_20220126_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPackageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, upload_to='documents')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('package_signup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='package.packagesignup')),
            ],
        ),
    ]
