# Generated by Django 3.2.8 on 2022-03-22 11:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0028_alter_frozenpackagedocument_final_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepackage',
            name='display_contract_length_months',
            field=models.PositiveIntegerField(help_text='Display version of contract length. Positive Integer eg. 12', null=True),
        ),
        migrations.AddField(
            model_name='basepackage',
            name='pricing_display',
            field=models.CharField(help_text='Display verison of pricing eg. £1000-£2000', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='frozenpackagedocument',
            name='final_zip',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/Users/ajrbyers/Code/intrepid/src/files'), upload_to='private_documents'),
        ),
    ]
