# Generated by Django 3.2.8 on 2022-03-22 11:55

from django.db import migrations, models
import package.models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0029_auto_20220322_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=package.models.package_images_upload_path),
        ),
    ]
