# Generated by Django 3.2.8 on 2022-04-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0030_alter_packagesignup_signup_date'),
        ('package', '0030_basepackage_image'),
    ]

    operations = [
    ]