# Generated by Django 3.2.8 on 2022-04-15 17:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0031_merge_20220415_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basepackage',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='basket',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Quotation name'),
        ),
        migrations.AlterField(
            model_name='frozenpackagedocument',
            name='final_zip',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/home/martin/Documents/Programming/intrepid/src/files'), upload_to='private_documents'),
        ),
    ]
