# Generated by Django 3.2.8 on 2022-04-19 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0031_merge_20220415_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proxy_signup_information',
            field=models.TextField(blank=True, help_text='Storage area for proxy signup information.', null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Basket name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='associated_user',
            field=models.ForeignKey(help_text='The account to whom the order belongs.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, help_text='Order numbers are automatically generated.'),
        ),
    ]
