# Generated by Django 3.2.8 on 2022-04-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0004_privateimage'),
        ('package', '0032_auto_20220419_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='private_images',
            field=models.ManyToManyField(to='intrepid.PrivateImage'),
        ),
    ]
