# Generated by Django 3.2.8 on 2022-04-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0032_auto_20220415_1704'),
        ('package', '0033_order_private_images'),
    ]

    operations = [
    ]
