# Generated by Django 3.2.8 on 2022-05-02 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0035_alter_frozenpackagedocument_final_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDocumentHistorical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, upload_to='documents')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('package_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.packagedocument')),
            ],
        ),
    ]
