# Generated by Django 3.2.8 on 2022-05-13 15:00

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
        ('package', '0037_alter_frozenpackagedocument_final_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='payment_processor',
            field=models.ForeignKey(blank=True, help_text='Optional allow a regional payment processor to handle invoicing for this banding', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.paymentprocessor'),
        ),
        migrations.AlterField(
            model_name='frozenpackagedocument',
            name='final_zip',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/Users/ajrbyers/Code/intrepid/src/files'), upload_to='private_documents'),
        ),
    ]
