# Generated by Django 3.2.8 on 2022-05-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_auto_20220513_1512'),
        ('package', '0038_auto_20220513_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='payment_processor',
        ),
        migrations.AddField(
            model_name='bandingtypecurrencyentry',
            name='payment_processor',
            field=models.ForeignKey(blank=True, help_text='Optional allow a regional payment processor to handle invoicing for this banding', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.paymentprocessor'),
        ),
    ]
