# Generated by Django 3.2.8 on 2022-05-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0039_auto_20220513_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesignup',
            name='banding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.banding'),
        ),
    ]
