# Generated by Django 3.2.8 on 2022-05-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0040_packagesignup_banding'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='recommended',
            field=models.BooleanField(default=False, help_text='If set, will be ordered by the Recommended option on the Packages page.'),
        ),
    ]
