# Generated by Django 3.2.8 on 2022-05-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0010_subjectvocab'),
        ('package', '0041_package_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepackage',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='vocab.SubjectVocab'),
        ),
    ]
