# Generated by Django 3.2.8 on 2022-05-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0042_basepackage_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='recommended',
        ),
        migrations.AddField(
            model_name='basepackage',
            name='recommended',
            field=models.BooleanField(default=False, help_text='If set, will be ordered by the Recommended option on the Packages page.'),
        ),
    ]
