# Generated by Django 3.2.8 on 2022-05-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0048_remove_banding_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandingtypeentry',
            name='redirect',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
