# Generated by Django 3.2.8 on 2022-05-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0049_bandingtypeentry_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandingtypeentry',
            name='redirect_display',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Redirect display'),
        ),
        migrations.AlterField(
            model_name='bandingtypeentry',
            name='redirect',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Redirect URL'),
        ),
    ]
