# Generated by Django 3.2.8 on 2022-06-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0012_alter_initiative_image'),
        ('package', '0051_alter_frozenpackagedocument_final_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='initiative',
            field=models.ForeignKey(blank=True, help_text='If signup inserted by initiaitve store here.', null=True, on_delete=django.db.models.deletion.CASCADE, to='initiatives.initiative'),
        ),
    ]
