# Generated by Django 3.2.8 on 2022-06-03 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0052_order_initiative'),
    ]

    operations = [
        migrations.AddField(
            model_name='metapackage',
            name='contact',
            field=models.ForeignKey(help_text='Contact person for this Meta Package.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
