# Generated by Django 3.2.8 on 2022-10-18 09:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0055_auto_20220626_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banding',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='banding',
            name='order',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='frozenpackagedocument',
            name='final_zip',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/Users/ajrbyers/Code/intrepid/src/files'), upload_to='private_documents'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/Users/ajrbyers/Code/intrepid/src/files'), upload_to='private_documents'),
        ),
    ]
