# Generated by Django 3.2.8 on 2022-07-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0055_auto_20220626_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='catch_all',
            field=models.BooleanField(default=False, help_text='Whether this currency is a grouping, such as EUR'),
        ),
    ]
