# Generated by Django 3.2.8 on 2022-10-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0056_auto_20221018_0946'),
        ('package', '0056_country_catch_all'),
    ]

    operations = [
    ]
