# Generated by Django 3.2.8 on 2023-01-12 12:46

import django.core.files.storage
from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0057_merge_0056_auto_20221018_0946_0056_country_catch_all'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banding',
            options={},
        ),
        migrations.AddField(
            model_name='bandingtype',
            name='description',
            field=django_bleach.models.BleachField(default='', help_text='Description that will appear on the banding selection section.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frozenpackagedocument',
            name='final_zip',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/home/ajrbyers/Code/intrepid/src/files'), upload_to='private_documents'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/home/ajrbyers/Code/intrepid/src/files'), upload_to='private_documents'),
        ),
    ]
