# Generated by Django 3.2.8 on 2023-02-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0058_auto_20230112_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='converted_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='converted_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
