# Generated by Django 3.2.8 on 2023-02-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0059_auto_20230212_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='converted_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
