# Generated by Django 3.2.8 on 2023-02-13 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0060_alter_order_converted_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='associated_user',
            field=models.ForeignKey(blank=True, help_text='The account to whom the order belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
