# Generated by Django 3.2.8 on 2023-02-13 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0062_auto_20230213_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='frozenpackagedocument',
            name='associated_session',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frozenpackagedocument',
            name='associated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
