# Generated by Django 3.2.8 on 2023-02-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0063_auto_20230213_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
