# Generated by Django 3.2.8 on 2024-02-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0067_auto_20240212_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='precalcminmax',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='package.package'),
            preserve_default=False,
        ),
    ]
