# Generated by Django 3.2.8 on 2024-02-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0068_precalcminmax_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='precalcminmax',
            name='meta_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='package.metapackage'),
        ),
        migrations.AlterField(
            model_name='precalcminmax',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='package.package'),
        ),
    ]
