# Generated by Django 3.2.8 on 2024-09-14 08:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0070_auto_20240701_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frozenpackagedocument',
            name='final_zip',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/Users/ajrbyers/Code/copim-intrepid/src/files'), upload_to='private_documents'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/Users/ajrbyers/Code/copim-intrepid/src/files'), upload_to='private_documents'),
        ),
    ]
