# Generated by Django 3.2.8 on 2025-10-20 09:46

import django.core.files.storage
from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0073_order_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandingtype',
            name='description_de',
            field=django_bleach.models.BleachField(help_text='Description that will appear on the banding selection section.', null=True),
        ),
        migrations.AddField(
            model_name='bandingtype',
            name='description_en',
            field=django_bleach.models.BleachField(help_text='Description that will appear on the banding selection section.', null=True),
        ),
    ]
