# Generated by Django 3.2.8 on 2025-10-20 09:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0074_auto_20251020_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandingtype',
            name='name_de',
            field=models.CharField(help_text='Public name of the Banding Type.#,', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bandingtype',
            name='name_en',
            field=models.CharField(help_text='Public name of the Banding Type.#,', max_length=255, null=True),
        ),
    ]
