# Generated by Django 3.2.8 on 2025-10-20 10:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0075_auto_20251020_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frozenpackagedocument',
            name='final_zip',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/home/ajrbyers/Code/intrepid/src/files'), upload_to='private_documents'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/home/ajrbyers/Code/intrepid/src/files'), upload_to='private_documents'),
        ),
    ]
