# Generated by Django 3.2.8 on 2026-02-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0076_auto_20251020_1005'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='banding',
            index=models.Index(fields=['package', 'banding_type'], name='banding_pkg_type_idx'),
        ),
        migrations.AddIndex(
            model_name='bandingtypecurrencyentry',
            index=models.Index(fields=['package', 'banding_type_entry'], name='btce_pkg_bte_idx'),
        ),
        migrations.AddIndex(
            model_name='bandingtypeentry',
            index=models.Index(fields=['package', 'banding_type'], name='bte_pkg_type_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['currency', 'catch_all'], name='country_currency_catchall_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['banding', 'country'], name='price_banding_country_idx'),
        ),
    ]
