---
- hosts: all
  tasks:
    - name: ensure postgres is at the latest version
      become: true
      apt:
        pkg:
          - ca-certificates
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - python3-dev
          - python3-psycopg2
        state: latest
    - name: start postgresql
      service:
          name: postgresql
          state: started
