# Generated by Django 3.2.4 on 2021-08-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210613_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fte',
            field=models.PositiveIntegerField(default='10000', help_text="Please enter your institution's full time equivalent so we can calculate basket costs."),
        ),
    ]
