# Generated by Django 3.2.4 on 2021-08-15 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0001_initial'),
        ('vocab', '0004_auto_20210815_1554'),
        ('accounts', '0003_profile_fte'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBandingChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('banding_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.bandingtype')),
                ('banding_type_vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.bandingvocab')),
            ],
        ),
    ]
