# Generated by Django 3.2.8 on 2021-12-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0022_alter_frozenpackagedocument_final_zip'),
        ('accounts', '0005_auto_20211024_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='package.country'),
        ),
    ]
