# Generated by Django 3.2.8 on 2022-04-19 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0035_alter_frozenpackagedocument_final_zip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_profile_default_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbandingchoices',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='accountbandingchoices',
            unique_together={('account', 'banding_type')},
        ),
    ]
