# Generated by Django 3.2.8 on 2022-05-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220419_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_new_books',
            field=models.BooleanField(default=False, verbose_name='Receive new book notifications'),
        ),
    ]
