# Generated by Django 3.2.8 on 2022-05-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_notify_new_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notify_new_books',
            field=models.BooleanField(default=False, verbose_name='Receive new book notifications for your institution (this is separate to your search feed)'),
        ),
    ]
