# Generated by Django 3.2.8 on 2022-05-24 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_notify_new_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
