# Generated by Django 3.2.8 on 2022-05-28 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_code',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True),
        ),
    ]
