# Generated by Django 3.2.8 on 2022-06-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_notify_targeted_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_new_attestations',
            field=models.BooleanField(default=True, verbose_name='If you are an initiative manager you will receive updates when new Standards are created.'),
        ),
    ]
