# Generated by Django 3.2.4 on 2021-08-11 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiatives', '0002_auto_20210706_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
