# Generated by Django 3.2.4 on 2021-10-30 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiatives', '0004_initiative_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='Initiatives', to=settings.AUTH_USER_MODEL),
        ),
    ]
