# Generated by Django 3.2.8 on 2022-03-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0006_initiative_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='short_code',
            field=models.CharField(help_text='Four letter short code.', max_length=4, null=True),
        ),
    ]
