# Generated by Django 3.2.8 on 2022-05-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0008_initiative_thoth_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='thoth_endpoint',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='A custom Thoth endpoint. You do not need to set this if using the primary Thoth server.'),
        ),
    ]
