# Generated by Django 3.2.8 on 2022-05-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0009_initiative_thoth_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='indexed_books',
            field=models.IntegerField(default=0, verbose_name='The number of books indexed by your service. If you are a publisher, leave this field at zero. If you are an index provider, like the DOAB, enter the number of books that you cover'),
        ),
    ]
