# Generated by Django 3.2.8 on 2022-05-24 12:57

from django.db import migrations, models
import initiatives.models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0011_initiative_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=initiatives.models.profile_images_upload_path, verbose_name='Logo image. Should be 335 x 100'),
        ),
    ]
