# Generated by Django 3.2.8 on 2023-03-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0012_alter_initiative_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
