# Generated by Django 3.2.8 on 2023-03-12 17:19

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0013_initiative_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='more_info',
            field=django_bleach.models.BleachField(blank=True, help_text='Appears on the Initiaitve/Package more info page.', null=True),
        ),
    ]
