# Generated by Django 3.2.8 on 2023-03-13 21:18

from django.db import migrations, models
import initiatives.models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0014_initiative_more_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to=initiatives.models.highlights_images_upload_path, verbose_name='Highlights images, should have a transparent background')),
            ],
        ),
    ]
