# Generated by Django 3.2.8 on 2023-03-13 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0015_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlights',
            name='initiative',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='initiatives.initiative'),
            preserve_default=False,
        ),
    ]
