# Generated by Django 3.2.8 on 2023-03-13 21:22

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0016_highlights_initiative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlights',
            name='body',
            field=django_bleach.models.BleachField(),
        ),
    ]
