# Generated by Django 3.2.8 on 2024-02-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0021_alter_initiative_more_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='exclude_from_thoth_filter',
            field=models.BooleanField(default=False, help_text='Check this to exclude this initiative from the Thoth search drop down.'),
        ),
    ]
