# Generated by Django 3.2.8 on 2021-11-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
