# Generated by Django 3.2.8 on 2022-03-27 11:10

from django.db import migrations
from django.conf import settings

def insert_sites(apps, schema_editor):
    """Populate the sites model"""
    Site = apps.get_model('sites', 'Site')
    Site.objects.all().delete()

    if settings.DEBUG:
        Site.objects.create(domain='localhost:8000', name='Dev OBC')
    else:
        Site.objects.create(domain='openbookcollective.org', name='Open Book Collective')


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0002_delete_emailtemplate'),
    ]

    operations = [
        migrations.RunPython(insert_sites)
    ]
