# Generated by Django 3.2.8 on 2022-04-29 11:17

import django.core.files.storage
from django.db import migrations, models
import django_bleach.models
import intrepid.models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0004_privateimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='enable_individual_package_signup',
            field=models.BooleanField(default=True, help_text='Enables or Disables signup to individual (initiative) packages.'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='enable_meta_package_signup',
            field=models.BooleanField(default=True, help_text='Enables or Disables signup to meta (collective) packages.'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='enable_signup',
            field=models.BooleanField(default=True, help_text='Enables or Disables signup across all packages and initiatives.'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='signup_disabled_notification',
            field=django_bleach.models.BleachField(blank=True, default='<p>Signup is currently disabled.', help_text='Displayed to users when signup is disabled.', null=True),
        ),
        migrations.AlterField(
            model_name='privateimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/Users/ajrbyers/Code/intrepid/src/files/private_images'), upload_to=intrepid.models.private_images_upload_path),
        ),
    ]
