# Generated by Django 3.2.8 on 2022-04-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0005_alter_privateimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
