# Generated by Django 3.2.8 on 2022-05-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0005_auto_20220429_1117'),
        ('intrepid', '0006_auto_20220429_1141'),
    ]

    operations = [
    ]
