# Generated by Django 3.2.8 on 2022-04-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0006_auto_20220429_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Platform Contact Email'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='site_name',
            field=models.CharField(blank=True, default='Open Book Collective', max_length=255, null=True, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL (full)'),
        ),
    ]
