# Generated by Django 3.2.8 on 2022-05-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0007_auto_20220429_1251'),
        ('intrepid', '0007_merge_0005_auto_20220429_1117_0006_auto_20220429_1141'),
    ]

    operations = [
    ]
