# Generated by Django 3.2.8 on 2022-05-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0009_alter_privateimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='youtube_embed',
            field=models.CharField(blank=True, default='//www.youtube.com/embed/Ut5_DA7Cihg', max_length=255, null=True, verbose_name='Youtube embed code for homepage video (e.g. //www.youtube.com/embed/Ut5_DA7Cihg)'),
        ),
    ]
