# Generated by Django 3.2.8 on 2022-05-13 16:27

import django.core.files.storage
from django.db import migrations, models
import intrepid.models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0010_sitesetup_youtube_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/Users/ajrbyers/Code/intrepid/src/files/private_images'), upload_to=intrepid.models.private_images_upload_path),
        ),
    ]
