# Generated by Django 3.2.8 on 2022-05-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0010_sitesetup_youtube_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='last_thoth_log',
            field=models.TextField(default=''),
        ),
    ]
