# Generated by Django 3.2.8 on 2022-05-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0011_sitesetup_last_thoth_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='last_thoth_log_date',
            field=models.DateTimeField(blank=None, default=None, null=True),
        ),
    ]
