# Generated by Django 3.2.8 on 2022-05-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0011_alter_privateimage_image'),
        ('intrepid', '0012_sitesetup_last_thoth_log_date'),
    ]

    operations = [
    ]
