# Generated by Django 3.2.8 on 2022-05-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0014_alter_privateimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='base_copyright_notice',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
