# Generated by Django 3.2.8 on 2022-05-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0015_sitesetup_base_copyright_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='base_copyright_notice',
            field=models.TextField(blank=True, default='All content &copy; 2022 Open Book Collective', null=True, verbose_name='Copyright statement to show in site footer'),
        ),
    ]
