# Generated by Django 3.2.8 on 2022-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0016_alter_sitesetup_base_copyright_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='board_of_stewards_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description of the Board of Stewards'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='management_team_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description of the Management Team'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='membership_committee_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description of the Membership Committee'),
        ),
    ]
