# Generated by Django 3.2.8 on 2022-05-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0017_alter_privateimage_image'),
        ('intrepid', '0017_auto_20220524_1257'),
    ]

    operations = [
    ]
