# Generated by Django 3.2.8 on 2023-01-01 15:38

import django.core.files.storage
from django.db import migrations, models
import intrepid.models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0022_auto_20221110_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='enable_standards',
            field=models.BooleanField(default=True, help_text='If disabled standards attestation will be hidden on the frontend.'),
        ),
        migrations.AlterField(
            model_name='privateimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/ajrbyers/Code/intrepid/src/files/private_images'), upload_to=intrepid.models.private_images_upload_path),
        ),
    ]
