# Generated by Django 3.2.8 on 2023-02-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0023_auto_20230101_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='fee_amount',
            field=models.PositiveIntegerField(default=5, help_text='Fee % added to each transaction.'),
        ),
    ]
