# Generated by Django 3.2.8 on 2023-02-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0024_sitesetup_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='fallback_currency',
            field=models.CharField(default='GBP', help_text="This is used as a fallback if we cannot get a conversion rate for a user's currency", max_length=3),
        ),
    ]
