# Generated by Django 3.2.8 on 2023-02-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0025_sitesetup_fallback_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='enable_search_on_packages',
            field=models.BooleanField(default=True),
        ),
    ]
