# Generated by Django 3.2.8 on 2023-02-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0026_sitesetup_enable_search_on_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='enable_your_quotes_link',
            field=models.BooleanField(default=True, help_text='If enabled a link for Your Quotes is displayed in the nav'),
        ),
    ]
