# Generated by Django 3.2.8 on 2023-06-21 19:32

import django.core.files.storage
from django.db import migrations, models
import intrepid.models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0027_sitesetup_enable_your_quotes_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/martin/Documents/Programming/intrepid/src/files/private_images'), upload_to=intrepid.models.private_images_upload_path),
        ),
    ]
