# Generated by Django 3.2.8 on 2024-07-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0028_alter_privateimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='finance_committee_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description of the Finance Committee'),
        ),
    ]
