# Generated by Django 3.2.8 on 2024-09-14 08:22

import django.core.files.storage
from django.db import migrations, models
import intrepid.models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0029_sitesetup_finance_committee_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/Users/ajrbyers/Code/copim-intrepid/src/files/private_images'), upload_to=intrepid.models.private_images_upload_path),
        ),
    ]
