# Generated by Django 3.2.8 on 2025-10-20 10:05

import django.core.files.storage
from django.db import migrations, models
import intrepid.models


class Migration(migrations.Migration):

    dependencies = [
        ('intrepid', '0031_alter_privateimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/ajrbyers/Code/intrepid/src/files/private_images'), upload_to=intrepid.models.private_images_upload_path),
        ),
    ]
