---
- hosts: all
  tasks:
    - name: ensure dependencies are at latest version
      become: true
      apt:
        pkg:
          - build-essential
          - virtualenv
          - python3-pip
          - python3-dev
          - libpq-dev
          - python3-psycopg2
          - acl
          - gunicorn
          - certbot
          - python3-certbot-nginx
        state: latest
