# Generated by Django 3.2.8 on 2026-05-30 09:27

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_bleach.models
import portal.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiatives', '0022_initiative_exclude_from_thoth_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/home/martin/Documents/Programming/intrepid/src/files'), upload_to=portal.models.portal_documents_upload_path)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('reporting_month', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_eligible_at', models.DateTimeField(blank=True, null=True)),
                ('notes', django_bleach.models.BleachField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', django_bleach.models.BleachField(blank=True)),
                ('requires_reporting_month', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('ordering', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProviderContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily digest'), ('weekly', 'Weekly digest'), ('monthly', 'Monthly digest'), ('off', 'Off')], default='immediate', max_length=20)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_contacts', to='initiatives.initiative')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible_at', models.DateTimeField()),
                ('frequency', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='portal.document')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='portal.providercontact')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTypePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='portal.documenttype')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.documenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='initiatives.initiative'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContactChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.initiative')),
                ('provider_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='portal.providercontact')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['eligible_at', 'sent_at'], name='portal_noti_eligibl_20bbec_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['document'], name='portal_noti_documen_9725c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttypepermission',
            unique_together={('document_type', 'group')},
        ),
    ]
