# Generated by Django 3.2.8 on 2026-05-30 09:45

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiatives', '0022_initiative_exclude_from_thoth_filter'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/home/martin/Documents/Programming/intrepid/src/files'), upload_to=portal.models.portal_bulk_zip_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notify_on_commit', models.BooleanField(default=False)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BulkImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('short_code', models.CharField(blank=True, max_length=10)),
                ('reporting_month', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('skipped', 'Skipped — please review'), ('error', 'Error'), ('duplicate', 'Duplicate')], default='ok', max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.documenttype')),
                ('initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='initiatives.initiative')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='portal.bulkimportjob')),
            ],
            options={
                'ordering': ('status', 'archive_path'),
            },
        ),
    ]
