# Generated by Django 3.2.8 on 2026-05-30 10:06

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_bulkimportjob_bulkimportrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='description_de',
            field=django_bleach.models.BleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='description_en',
            field=django_bleach.models.BleachField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='name_de',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='name_en',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
    ]
