# Generated by Django 3.2.8 on 2026-06-01 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0023_initiative_highlights_translations'),
        ('portal', '0008_portal_text_phase2'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='initiatives.initiative')),
            ],
            options={
                'verbose_name_plural': 'Initiative aliases',
                'ordering': ('alias',),
                'unique_together': {('initiative', 'alias')},
            },
        ),
    ]
