# Generated by Django 3.2.8 on 2026-07-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_portal_admin_dashboard_tile'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercontact',
            name='is_login_invite',
            field=models.BooleanField(default=False),
        ),
    ]
