# Generated by Django 3.2.8 on 2026-07-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_refresh_stale_contract_name_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercontact',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], default='en', max_length=10),
        ),
    ]
