# Generated by Django 3.2.4 on 2021-07-04 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_bleach.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Text displayed in <h1> for this page.', max_length=255)),
                ('body', django_bleach.models.BleachField(help_text='Contents of the page, HTML.')),
                ('display', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_page_related', related_query_name='cms_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Text displayed in <h1> for this page.', max_length=255)),
                ('body', django_bleach.models.BleachField(help_text='Contents of the page, HTML.')),
                ('public', models.BooleanField(default=False, help_text='Mark this update as public facing. Otherwise it will only be available to supporters')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_update_related', related_query_name='cms_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Text displayed in <h1> for this page.', max_length=255)),
                ('body', django_bleach.models.BleachField(help_text='Contents of the page, HTML.')),
                ('public', models.BooleanField(default=False, help_text='Mark this update as public facing. Otherwise it will only be available to supporters')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.update')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_updatehistory_related', related_query_name='cms_updatehistorys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Text displayed in <h1> for this page.', max_length=255)),
                ('body', django_bleach.models.BleachField(help_text='Contents of the page, HTML.')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_pagehistory_related', related_query_name='cms_pagehistorys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
