# Generated by Django 3.2.4 on 2021-07-04 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pagehistory',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='update',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='updatehistory',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='Text displayed in h1 for this page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='pagehistory',
            name='title',
            field=models.CharField(help_text='Text displayed in h1 for this page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='update',
            name='title',
            field=models.CharField(help_text='Text displayed in h1 for this page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='updatehistory',
            name='title',
            field=models.CharField(help_text='Text displayed in h1 for this page.', max_length=255),
        ),
    ]
