# Generated by Django 3.2.4 on 2021-08-29 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0002_auto_20210704_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Text displayed in h1 for this page.', max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('display', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', django_bleach.models.BleachField(help_text='Contents of the page, HTML.')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='pagehistory',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pagehistory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='update',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='updatehistory',
            name='update',
        ),
        migrations.RemoveField(
            model_name='updatehistory',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageHistory',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
        migrations.DeleteModel(
            name='UpdateHistory',
        ),
        migrations.AddField(
            model_name='pageupdate',
            name='current_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_version', to='cms.version'),
        ),
        migrations.AddField(
            model_name='pageupdate',
            name='other_versions',
            field=models.ManyToManyField(blank=True, to='cms.Version'),
        ),
        migrations.AddField(
            model_name='pageupdate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_pageupdate_related', related_query_name='cms_pageupdates', to=settings.AUTH_USER_MODEL),
        ),
    ]
