# Generated by Django 3.2.4 on 2021-08-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_pageupdate_is_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageupdate',
            name='sequence',
            field=models.PositiveIntegerField(default=99),
        ),
    ]
