# Generated by Django 3.2.4 on 2021-08-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0004_initiative_active'),
        ('cms', '0006_version_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageupdate',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='initiatives.initiative'),
        ),
    ]
