# Generated by Django 3.2.4 on 2021-09-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_pageupdate_initiative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageupdate',
            options={'ordering': ('sequence', 'title')},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='pageupdate',
            name='display',
            field=models.BooleanField(default=False, help_text='Check to make this live.', verbose_name='Display'),
        ),
        migrations.AlterField(
            model_name='pageupdate',
            name='sequence',
            field=models.PositiveIntegerField(default=99, help_text='Used to determine page order. Pages with the same sequence and then ordered by title.'),
        ),
    ]
