# Generated by Django 3.2.8 on 2022-04-15 17:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20210907_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeAreProfileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('affiliation_line', models.CharField(blank=True, max_length=255, null=True)),
                ('police_mugshot', models.ImageField(blank=True, null=True, upload_to='', verbose_name=accounts.models.profile_images_upload_path)),
                ('section', models.CharField(max_length=255)),
            ],
        ),
    ]
