# Generated by Django 3.2.8 on 2022-04-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_whoweareprofileitem_police_mugshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoweareprofileitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
