# Generated by Django 3.2.8 on 2022-04-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_whoweareprofileitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteWideNewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('update_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.pageupdate')),
            ],
        ),
    ]
