# Generated by Django 3.2.8 on 2022-04-17 17:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_sitewidenewsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageupdate',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_images_upload_path, verbose_name='Page Thumbnail'),
        ),
    ]
