# Generated by Django 3.2.8 on 2022-04-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_pageupdate_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageupdate',
            name='abstract_paragraph',
            field=models.TextField(blank=True, null=True, verbose_name='Page abstract paragraph (a brief summary)'),
        ),
    ]
