# Generated by Django 3.2.8 on 2022-04-18 15:22

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_pageupdate_abstract_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='first_paragraph',
            field=django_bleach.models.BleachField(default='', help_text='The first paragraph of the page, HTML'),
        ),
        migrations.AddField(
            model_name='version',
            name='pre_break_content',
            field=django_bleach.models.BleachField(default='', help_text='A second paragraph that will be displayed before the image break'),
        ),
        migrations.AddField(
            model_name='version',
            name='pull_quote',
            field=django_bleach.models.BleachField(default='', help_text='The text to display in the pull-quote'),
        ),
        migrations.AlterField(
            model_name='version',
            name='body',
            field=django_bleach.models.BleachField(default='', help_text='The rest of the page or news update, HTML.'),
        ),
    ]
