# Generated by Django 3.2.8 on 2022-04-19 15:41

from django.db import migrations, models
import django.db.models.deletion
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0007_initiative_short_code'),
        ('cms', '0015_auto_20220418_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='body',
            field=django_bleach.models.BleachField(default='', help_text='The rest of the page or news update, HTML. We recommend beginning this with a heading tag.'),
        ),
        migrations.AlterField(
            model_name='version',
            name='pre_break_content',
            field=django_bleach.models.BleachField(default='', help_text='A second paragraph that will be displayed before the image break. We recommend beginning this with a heading tag.'),
        ),
        migrations.CreateModel(
            name='PrimaryInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility', to='cms.pageupdate')),
                ('documentation_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='cms.pageupdate')),
                ('funding_model_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_model', to='cms.pageupdate')),
                ('governance_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance', to='cms.pageupdate')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.initiative')),
                ('privacy_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to='cms.pageupdate')),
                ('terms_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='cms.pageupdate')),
                ('values_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='cms.pageupdate')),
                ('what_we_do_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_we_do', to='cms.pageupdate')),
                ('why_support_oa_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_support_oa', to='cms.pageupdate')),
            ],
        ),
    ]
