# Generated by Django 3.2.8 on 2022-04-19 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20220419_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryinitiative',
            name='accessibility_page',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessibility', to='cms.pageupdate'),
        ),
        migrations.AlterField(
            model_name='primaryinitiative',
            name='documentation_page',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='cms.pageupdate'),
        ),
        migrations.AlterField(
            model_name='primaryinitiative',
            name='funding_model_page',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_model', to='cms.pageupdate'),
        ),
        migrations.AlterField(
            model_name='primaryinitiative',
            name='governance_page',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='governance', to='cms.pageupdate'),
        ),
        migrations.AlterField(
            model_name='primaryinitiative',
            name='privacy_page',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to='cms.pageupdate'),
        ),
        migrations.AlterField(
            model_name='primaryinitiative',
            name='terms_page',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='cms.pageupdate'),
        ),
        migrations.AlterField(
            model_name='primaryinitiative',
            name='values_page',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='cms.pageupdate'),
        ),
        migrations.AlterField(
            model_name='primaryinitiative',
            name='what_we_do_page',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='what_we_do', to='cms.pageupdate'),
        ),
        migrations.AlterField(
            model_name='primaryinitiative',
            name='why_support_oa_page',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='why_support_oa', to='cms.pageupdate'),
        ),
    ]
