# Generated by Django 3.2.8 on 2022-04-29 12:51

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20220419_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quotation', django_bleach.models.BleachField(blank=True, max_length=255, null=True)),
                ('person_attribution', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_attribution', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
