# Generated by Django 3.2.8 on 2022-04-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_homepagequote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagequote',
            name='quotation',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
