# Generated by Django 3.2.8 on 2022-04-29 15:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_alter_homepagequote_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagequote',
            name='organization_logo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_images_upload_path, verbose_name='Associated quote image (145 x 145)'),
        ),
    ]
