# Generated by Django 3.2.8 on 2022-05-08 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20220508_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryinitiative',
            name='supporting_libraries_page',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_libraries', to='cms.pageupdate'),
        ),
        migrations.AddField(
            model_name='primaryinitiative',
            name='transforming_publishing_page',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transforming_publishing', to='cms.pageupdate'),
        ),
    ]
