# Generated by Django 3.2.8 on 2022-05-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0032_alter_thothsearch_options'),
        ('cms', '0024_auto_20220508_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageupdate',
            name='target_institution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='thoth.rorrecord', verbose_name='Whether this update is visible only to people at a specific university'),
        ),
    ]
