# Generated by Django 3.2.8 on 2022-05-24 12:57

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_pageupdate_target_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='first_paragraph',
            field=django_bleach.models.BleachField(default='', help_text='The first paragraph of the page, HTML. Do NOT start this paragraph with a link.'),
        ),
    ]
