# Generated by Django 3.2.8 on 2022-05-29 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thoth', '0032_alter_thothsearch_options'),
        ('initiatives', '0012_alter_initiative_image'),
        ('cms', '0026_alter_version_first_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoth.work')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.initiative')),
            ],
        ),
    ]
