# Generated by Django 3.2.8 on 2022-05-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_featuredbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredbook',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
