# Generated by Django 3.2.8 on 2022-06-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_featuredbook_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageupdate',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Used to block multiple Update notification sends.'),
        ),
    ]
