# Generated by Django 3.2.8 on 2022-10-08 14:34

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_alter_version_pull_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='pre_break_content',
            field=django_bleach.models.BleachField(blank=True, default='', help_text='A second paragraph that will be displayed before the image break. We recommend beginning this with a heading tag.', null=True),
        ),
    ]
