# Generated by Django 3.2.8 on 2022-10-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_alter_version_pre_break_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='show_quote_icons',
            field=models.BooleanField(default=True),
        ),
    ]
