# Generated by Django 3.2.8 on 2022-11-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_version_show_quote_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoweareprofileitem',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
