# Generated by Django 3.2.8 on 2022-12-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_whoweareprofileitem_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=20)),
                ('body', models.TextField()),
                ('help_text', models.TextField()),
            ],
        ),
    ]
