# Generated by Django 3.2.8 on 2022-12-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_sitetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetext',
            name='rich_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitetext',
            name='key',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
