# Generated by Django 3.2.8 on 2023-05-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_auto_20221218_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryinitiative',
            name='supporters_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporters', to='cms.pageupdate'),
        ),
    ]
