# Generated by Django 3.2.8 on 2024-08-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_primaryinitiative_supporters_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageupdate',
            name='url_expression',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL expression'),
        ),
    ]
