# Generated by Django 3.2.8 on 2024-09-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_pageupdate_url_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetext',
            name='body_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='rich_text_de',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='rich_text_en',
            field=models.BooleanField(default=False),
        ),
    ]
