# Generated by Django 3.2.8 on 2024-09-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0039_auto_20240914_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetext',
            name='key',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
