# Generated by Django 3.2.8 on 2024-11-25 11:47

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_alter_sitetext_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagequote',
            name='organization_attribution_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagequote',
            name='organization_attribution_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagequote',
            name='person_attribution_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagequote',
            name='person_attribution_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagequote',
            name='pill_name_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagequote',
            name='pill_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagequote',
            name='quotation_de',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagequote',
            name='quotation_en',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pageupdate',
            name='abstract_paragraph_de',
            field=models.TextField(blank=True, null=True, verbose_name='Page abstract paragraph (a brief summary)'),
        ),
        migrations.AddField(
            model_name='pageupdate',
            name='abstract_paragraph_en',
            field=models.TextField(blank=True, null=True, verbose_name='Page abstract paragraph (a brief summary)'),
        ),
        migrations.AddField(
            model_name='pageupdate',
            name='title_de',
            field=models.CharField(help_text='Text displayed in h1 for this page.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pageupdate',
            name='title_en',
            field=models.CharField(help_text='Text displayed in h1 for this page.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='body_de',
            field=django_bleach.models.BleachField(default='', help_text='The rest of the page or news update, HTML. We recommend beginning this with a heading tag.', null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='body_en',
            field=django_bleach.models.BleachField(default='', help_text='The rest of the page or news update, HTML. We recommend beginning this with a heading tag.', null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='first_paragraph_de',
            field=django_bleach.models.BleachField(default='', help_text='The first paragraph of the page, HTML. Do NOT start this paragraph with a link.', null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='first_paragraph_en',
            field=django_bleach.models.BleachField(default='', help_text='The first paragraph of the page, HTML. Do NOT start this paragraph with a link.', null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='pre_break_content_de',
            field=django_bleach.models.BleachField(blank=True, default='', help_text='A second paragraph that will be displayed before the image break. We recommend beginning this with a heading tag.', null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='pre_break_content_en',
            field=django_bleach.models.BleachField(blank=True, default='', help_text='A second paragraph that will be displayed before the image break. We recommend beginning this with a heading tag.', null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='pull_quote_de',
            field=models.TextField(blank=True, default='', help_text='The text to display in the pull-quote', null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='pull_quote_en',
            field=models.TextField(blank=True, default='', help_text='The text to display in the pull-quote', null=True),
        ),
        migrations.AddField(
            model_name='whoweareprofileitem',
            name='bio_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whoweareprofileitem',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
