# Generated by Django 3.2.8 on 2022-05-13 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0037_alter_frozenpackagedocument_final_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('countries', models.ManyToManyField(help_text='Countries covered by this payment processor.', to='package.Country')),
                ('managers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignupInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('sent', 'Invoice Sent'), ('paid', 'Invoice Paid')], default='new', max_length=4)),
                ('payment_processor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoicing.paymentprocessor')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('new', 'New'), ('sent', 'Invoice Sent'), ('paid', 'Invoice Paid')], default='new', max_length=4)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('sent', 'Invoice Sent'), ('paid', 'Invoice Paid')], default='new', max_length=4)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.signupinvoice')),
            ],
        ),
    ]
