# Generated by Django 3.2.8 on 2022-05-13 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0038_auto_20220513_1500'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupinvoice',
            name='signup',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='package.packagesignup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signupinvoice',
            name='payment_processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.paymentprocessor'),
        ),
    ]
