# Generated by Django 3.2.8 on 2022-05-13 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_auto_20220513_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicelog',
            old_name='from_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='invoicelog',
            name='to_status',
        ),
        migrations.AddField(
            model_name='invoicelog',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
