# Generated by Django 3.2.8 on 2021-11-28 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0016_merge_20211128_1103'),
        ('initiatives', '0005_alter_initiative_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Please enter this contact's full name.", max_length=300)),
                ('email', models.EmailField(max_length=255)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.initiative')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AccessLogExportCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_to', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('active', models.BooleanField(default=True)),
                ('affiliated_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('organisation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='initiatives.initiative')),
            ],
            options={
                'ordering': ('-active',),
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('grant', 'Grant'), ('revoke', 'Revoke')], max_length=10)),
                ('date_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_range', models.TextField(blank=True, null=True)),
                ('payment_handler', models.TextField(blank=True, null=True)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.packagesignup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_stamp',),
            },
        ),
    ]
