# Generated by Django 3.2.4 on 2021-10-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_auto_20210815_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandingvocab',
            name='text',
            field=models.TextField(blank=True, help_text='For non-fte banding types add the text here.', null=True),
        ),
    ]
