# Generated by Django 3.2.8 on 2021-12-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0005_alter_bandingvocab_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandingvocab',
            name='text',
            field=models.CharField(blank=True, help_text='For non-fte banding types add the text here.', max_length=255, null=True),
        ),
    ]
