# Generated by Django 3.2.8 on 2021-12-05 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0025_packagesignuporderformanswer'),
        ('vocab', '0007_standardvocab'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageStandardAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_url', models.URLField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.standardvocab')),
            ],
        ),
    ]
