# Generated by Django 3.2.8 on 2021-12-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0026_auto_20211206_1721'),
        ('vocab', '0008_packagestandardattestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagestandardattestation',
            name='details_url',
            field=models.URLField(blank=True, null=True, verbose_name='The URL detailing your implementation of this policy'),
        ),
        migrations.AlterField(
            model_name='packagestandardattestation',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards_attested', to='package.package', verbose_name='Standards to which this package attests'),
        ),
    ]
