# Generated by Django 3.2.8 on 2022-05-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0009_auto_20211206_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectVocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
