# Generated by Django 3.2.8 on 2022-05-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0010_subjectvocab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectvocab',
            options={'ordering': ('name',)},
        ),
    ]
