# Generated by Django 3.2.8 on 2022-05-24 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0045_alter_frozenpackagedocument_final_zip'),
        ('vocab', '0011_alter_subjectvocab_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardvocab',
            name='text',
            field=models.TextField(blank=True, help_text='The text of the attested standard.', null=True),
        ),
        migrations.CreateModel(
            name='AttestationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_or_remove', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], max_length=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.standardvocab')),
            ],
        ),
    ]
