# Generated by Django 3.2.8 on 2022-05-24 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0012_auto_20220524_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attestationhistory',
            options={'verbose_name_plural': 'Attestation histories'},
        ),
        migrations.AddField(
            model_name='attestationhistory',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
