# Generated by Django 3.2.8 on 2022-05-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0013_auto_20220524_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attestationhistory',
            options={'ordering': ('-date_time',), 'verbose_name_plural': 'Attestation histories'},
        ),
        migrations.AlterModelOptions(
            name='packagestandardattestation',
            options={'ordering': ('standard__standard_name',)},
        ),
    ]
